### ISSUE TITLE
Does not install via setup.py due to diffpy.Structure

### ISSUE THREAD

**Issue by mikapfl** [ornlneutronimaging/braggedgemodeling#23]
Hi,

I tried installing via 
```bash
python3 setup.py install --user
```
as suggested in the [docs](https://ornlneutronimaging.github.io/braggedgemodeling/installation.html#using-setup-py).
However, that failed because the `diffpy.Structure` package available from https://pypi.org/project/diffpy.Structure/ is not compatible with python3. Without it, `bem` is not importable. I think you have to add documentation about where I would acquire a `diffpy.Structure` version compatible to `bem` and how to install that.

Cheers,

Mika

**Comment by katyhuff** [comment]
ditto.

**Comment by yxqd** [comment]
@mikapfl @katyhuff I have updated the [installation instructions](https://ornlneutronimaging.github.io/braggedgemodeling/installation.html). It is now clarified that `conda` is the preferred installation method. The [using setup.py](https://ornlneutronimaging.github.io/braggedgemodeling/installation.html#using-setup-py) section is expanded with details, especially on installing [diffpy.structure python 3](https://github.com/diffpy/diffpy.structure/tree/python3) from source. Please check. Thanks.

**Comment by katyhuff** [comment]
Weirdly, the setup.py instructions didn't work for me until I neglected --user in the diffpy.structure setup.py install. Probably something about my (admittedly, increasingly complex) various conda environments. 

Works now, tests pass.

**Comment by yxqd** [comment]
Thanks @katyhuff for checking!

**Comment by mikapfl** [comment]
Hi,

works now for me, only left issue is that the last line, which currently reads
```
$ cd braggedgemodeling && python setup.py install --user
```
should probably read
```
$ cd braggedgemodeling && python3 setup.py install --user
```
to be consistent with the rest of the instructions, which also use python**3**

Cheers

Mika

**Comment by mikapfl** [comment]
Looks good for me now!
